### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by coanpape** [creativetimofficial/light-bootstrap-dashboard-angular-cli#2]
I was attempting to use this project to help get me past some issues in converting the lbd pro angular 2 dashboard to the angular CLI.  
I performed the following steps:

1. ng new light-bootstrap-dashboard-angular-cli-master
2. cd light-bootstrap-dashboard-angular-cli-master
3. ng serve --open
4. Verified that the empty app worked
5.  overlayed the empty app folder with the contents of light-bootstrap-dashboard-angular-cli-master.zip
6. ng serve --open
7. the first time I tried the ng serve on the lbd project the browser opened with errors on jquery (like I have been experiencing and hoping you had found a work around for)
8. I stopped the cmd script process and restarted it
9. ng serve --open
this time it did not compile but reported the following errors:

ERROR in D:/Learning/angular/cli/light-bootstrap-dashboard-angular-cli-master/src/main.ts (5,20): Cannot find name 'require'.

ERROR in D:/Learning/angular/cli/light-bootstrap-dashboard-angular-cli-master/src/main.ts (5,20): Cannot find name 'require'.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'jquery' in 'D:\Learning\angular\cli\light-bootstrap-dashboard-angular-cli-master\src'
 @ ./src/main.ts 5:19-36
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

Were my install steps what is intended?

**Comment by chelaruc** [comment]
updated to 1.4.0
