### ISSUE TITLE
Index File Issue

### ISSUE THREAD

**Issue by ManojKiranA** [creativetimofficial/light-bootstrap-dashboard-angular-cli#3]
![fault](https://user-images.githubusercontent.com/30294553/34648849-4ed1035a-f3c8-11e7-9811-53d2444e39a7.png)
Index file is saying that
loading

**Comment by chelaruc** [comment]
Hi, @AManojKiran! Thank you for using our product! In the documentation you have a section for getting started, see that section.

Best,
Ciprian
